#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libqrtr-glib
Version  : 1.0.0
Release  : 1
URL      : https://www.freedesktop.org/software/libqmi/libqrtr-glib-1.0.0.tar.xz
Source0  : https://www.freedesktop.org/software/libqmi/libqrtr-glib-1.0.0.tar.xz
Summary  : Library to use and monitor the QRTR bus
Group    : Development/Tools
License  : LGPL-2.1
Requires: libqrtr-glib-data = %{version}-%{release}
Requires: libqrtr-glib-lib = %{version}-%{release}
Requires: libqrtr-glib-license = %{version}-%{release}
BuildRequires : docbook-xml
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)

%description
libqrtr-glib is a glib-based library to use and manage the QRTR (Qualcomm
IPC Router) bus.

%package data
Summary: data components for the libqrtr-glib package.
Group: Data

%description data
data components for the libqrtr-glib package.


%package dev
Summary: dev components for the libqrtr-glib package.
Group: Development
Requires: libqrtr-glib-lib = %{version}-%{release}
Requires: libqrtr-glib-data = %{version}-%{release}
Provides: libqrtr-glib-devel = %{version}-%{release}
Requires: libqrtr-glib = %{version}-%{release}

%description dev
dev components for the libqrtr-glib package.


%package doc
Summary: doc components for the libqrtr-glib package.
Group: Documentation

%description doc
doc components for the libqrtr-glib package.


%package lib
Summary: lib components for the libqrtr-glib package.
Group: Libraries
Requires: libqrtr-glib-data = %{version}-%{release}
Requires: libqrtr-glib-license = %{version}-%{release}

%description lib
lib components for the libqrtr-glib package.


%package license
Summary: license components for the libqrtr-glib package.
Group: Default

%description license
license components for the libqrtr-glib package.


%prep
%setup -q -n libqrtr-glib-1.0.0
cd %{_builddir}/libqrtr-glib-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1621350070
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1621350070
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libqrtr-glib
cp %{_builddir}/libqrtr-glib-1.0.0/COPYING.LIB %{buildroot}/usr/share/package-licenses/libqrtr-glib/01a6b4bf79aca9b556822601186afab86e8c4fbf
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Qrtr-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/libqrtr-glib/libqrtr-glib.h
/usr/include/libqrtr-glib/qrtr-bus.h
/usr/include/libqrtr-glib/qrtr-client.h
/usr/include/libqrtr-glib/qrtr-node.h
/usr/include/libqrtr-glib/qrtr-utils.h
/usr/include/libqrtr-glib/qrtr-version.h
/usr/lib64/libqrtr-glib.so
/usr/lib64/pkgconfig/qrtr-glib.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/libqrtr-glib/QrtrBus.html
/usr/share/gtk-doc/html/libqrtr-glib/QrtrClient.html
/usr/share/gtk-doc/html/libqrtr-glib/QrtrNode.html
/usr/share/gtk-doc/html/libqrtr-glib/annotation-glossary.html
/usr/share/gtk-doc/html/libqrtr-glib/api-index-1-0.html
/usr/share/gtk-doc/html/libqrtr-glib/api-index-full.html
/usr/share/gtk-doc/html/libqrtr-glib/ch01.html
/usr/share/gtk-doc/html/libqrtr-glib/home.png
/usr/share/gtk-doc/html/libqrtr-glib/index.html
/usr/share/gtk-doc/html/libqrtr-glib/left-insensitive.png
/usr/share/gtk-doc/html/libqrtr-glib/left.png
/usr/share/gtk-doc/html/libqrtr-glib/libqrtr-glib-qrtr-utils.html
/usr/share/gtk-doc/html/libqrtr-glib/libqrtr-glib-qrtr-version.html
/usr/share/gtk-doc/html/libqrtr-glib/libqrtr-glib.devhelp2
/usr/share/gtk-doc/html/libqrtr-glib/object-tree.html
/usr/share/gtk-doc/html/libqrtr-glib/right-insensitive.png
/usr/share/gtk-doc/html/libqrtr-glib/right.png
/usr/share/gtk-doc/html/libqrtr-glib/style.css
/usr/share/gtk-doc/html/libqrtr-glib/up-insensitive.png
/usr/share/gtk-doc/html/libqrtr-glib/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libqrtr-glib.so.0
/usr/lib64/libqrtr-glib.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libqrtr-glib/01a6b4bf79aca9b556822601186afab86e8c4fbf
